FROM almalinux:8
ADD hello.txt /tmp/
ADD https://raw.githubusercontent.com/pkumarbdevops/dockerfiles/main/commands.MD /tmp/I:\devops\daws-74s\repos\Shell-Script\dockerfiles\dockerfiles\ADD\sample-1.tar
ADD sample-1.tar /tmp/